# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directories:
      - "/admin"
      - "/CheckEngine/CheckEngineRunner"
      - "/CheckEngine/DatabaseAccess"
      - "/Logger"
      - "/Quartz/Quartz.Plugins.RecentHistory"
      - "/Quartz/SilkierQuartz"
    schedule:
      interval: "daily" 
    open-pull-requests-limit: 25
    ignore:
      - dependency-name: "Microsoft.Extensions.FileProviders.Embedded"
        versions: [">=9.0.0"]
      - dependency-name: "Microsoft.Extensions.FileProviders.Physical"
        versions: [">=9.0.0"]
      - dependency-name: "AWSSDK.Core"
        versions: [">=4"]
      - dependency-name: "AWSSDK.S3"
        versions: [">=4"]
      - dependency-name: "Swashbuckle.AspNetCore.Swagger"
        versions: [">=7.0.0"]
      - dependency-name: "Swashbuckle.AspNetCore.SwaggerGen"
        versions: [">=7.0.0"]
      - dependency-name: "Swashbuckle.AspNetCore.Annotations"
        versions: [">=7.0.0"]
      - dependency-name: "Microsoft.Windows.Compatibility"
        versions: [">=7.0.0"]
      - dependency-name: "Serilog.AspNetCore"
        versions: [">=7.0.0"]
      - dependency-name: "Handlebars.Net"
        versions: [">=2.0.0"]        
