<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotNetEnv" Version="3.1.1" />
    <PackageReference Include="Quartz" Version="3.14.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CheckEngine\CheckEngine.csproj" />
    <ProjectReference Include="..\DM\DM.csproj" />
  </ItemGroup>

</Project>
