name: Develop Branch Workflow

on:
  push:
    branches: [develop]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - ".gitignore"

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    environment:
      name: Dev
      url: https://easey-dev.app.cloud.gov/quartz
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Build
        run: |
          echo "--------------------------------------"
          echo "---------- dotnet/build.sh -----------"
          echo "--------------------------------------"

          echo "Installing dependencies..."
          cd admin
          dotnet restore

          echo "Building..."
          CI=false dotnet build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_DEV_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_DEV_DEPLOYMENT_SVC_PWD }}
      - name: Init Application
        run: devops/scripts/cf-app-init.sh
      - name: Configure Env Vars (secrets)
        run: scripts/environment-variables-secrets.sh
        env:
          QUARTZ_API_KEY: ${{ secrets.API_KEY }}
          BULK_FILES_AWS_ACCESS_KEY_ID: ${{ secrets.BULK_DATA_S3_AWS_ACCESS_KEY_ID }}
          BULK_FILES_AWS_SECRET_ACCESS_KEY: ${{ secrets.BULK_DATA_S3_AWS_SECRET_ACCESS_KEY }}
          QUARTZ_API_SECRET_TOKEN: ${{ secrets.API_SECRET_TOKEN }}
          QUARTZ_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      - name: Deploy
        run: devops/scripts/deploy.sh
