name: Develop Branch Workflow

on:
  push:
    branches: [develop]
    paths-ignore:
      - '.github/**'

jobs:
  Build-Test-Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Checkout devops repo
        uses: actions/checkout@v2
        with:
          repository: US-EPA-CAMD/devops
          path: devops
      - name: Configure Env Vars
        run: devops/scripts/environment-variables.sh
        env:
          ENV_VAR_PREFIX: EASEY
      - name: Build
        run: |
          echo "--------------------------------------"
          echo "---------- dotnet/build.sh -----------"
          echo "--------------------------------------"

          echo "Installing dependencies..."
          cd admin
          dotnet restore

          echo "Building..."
          CI=false dotnet build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Run Unit Tests
      #   run: |
      #     echo "--------------------------------------"
      #     echo "-------- dotnet/unit-tests.sh --------"
      #     echo "--------------------------------------"

      #     echo "Running Unit tests... "
      #     cd admin
      #     CI=true dotnet run tests
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      - name: Install cf cli
        run: devops/scripts/install-cf-cli.sh
      - name: Login to cloud.gov
        run: devops/scripts/cf-login.sh
        env:
          CF_USERNAME: ${{ secrets.CF_DEV_DEPLOYMENT_SVC }}
          CF_PASSWORD: ${{ secrets.CF_DEV_DEPLOYMENT_SVC_PWD }}
      - name: Deploy
        run: devops/scripts/deploy.sh
